GET http://localhost:3001/api/blogs
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im9sbGlwbzIiLCJpZCI6IjYxNDA5YWI1ZDAwNTRlMjMxYThhMDgyYSIsImlhdCI6MTYzMTY4MTY0MX0.8f-8mR5dpHa2Zvrtq3LhF2poxYbfHi62aalBgr3PKpc